"""Immutable metadata for every version 1 RepoInsight rule."""

from __future__ import annotations

from ..models import Category, Confidence, RuleDefinition, Severity


def _rule(
    id: str,
    category: Category,
    title: str,
    evidence: str,
    severity: Severity,
    deduction: float,
    cap: float,
    limitations: str,
    remediation: str,
    *,
    threshold_key: str | tuple[str, ...] | None = None,
    threshold_value: int | float | tuple[int | float, ...] | None = None,
    confidence: Confidence = Confidence.HIGH,
    heuristic: bool = False,
) -> RuleDefinition:
    return RuleDefinition(
        id=id,
        category=category,
        title=title,
        evidence_definition=evidence,
        default_enabled=True,
        severity=severity,
        default_deduction=deduction,
        per_rule_cap=cap,
        threshold_key=threshold_key,
        threshold_value=threshold_value,
        confidence=confidence,
        limitations=limitations,
        remediation=remediation,
        heuristic=heuristic,
    )


RULE_CATALOG = (
    _rule(
        "RI-MAINT-001",
        Category.MAINTAINABILITY,
        "High cyclomatic complexity",
        "Function or method static cyclomatic complexity is at least 15.",
        Severity.MEDIUM,
        3,
        15,
        "Static branch complexity only; runtime complexity and design intent are not assessed.",
        "Split branches or extract focused helpers.",
        threshold_key="complexity",
        threshold_value=15,
        confidence=Confidence.MEDIUM,
        heuristic=True,
    ),
    _rule(
        "RI-MAINT-002",
        Category.MAINTAINABILITY,
        "Large function or method",
        "Function or method physical LOC is greater than 75.",
        Severity.MEDIUM,
        2,
        10,
        "Size is a proxy and is not proof of poor design.",
        "Decompose cohesive units where it improves clarity.",
        threshold_key="function_loc",
        threshold_value=75,
        confidence=Confidence.MEDIUM,
        heuristic=True,
    ),
    _rule(
        "RI-MAINT-003",
        Category.MAINTAINABILITY,
        "Large class",
        "Class physical LOC is greater than 500.",
        Severity.MEDIUM,
        3,
        9,
        "Size is not proof of poor design.",
        "Split responsibilities after review.",
        threshold_key="class_loc",
        threshold_value=500,
        confidence=Confidence.MEDIUM,
        heuristic=True,
    ),
    _rule(
        "RI-MAINT-004",
        Category.MAINTAINABILITY,
        "Large Python module",
        "Python module physical LOC is greater than 1000.",
        Severity.MEDIUM,
        3,
        9,
        "Cohesion is not assessed.",
        "Split by responsibility when useful.",
        threshold_key="module_loc",
        threshold_value=1000,
        confidence=Confidence.MEDIUM,
        heuristic=True,
    ),
    _rule(
        "RI-MAINT-005",
        Category.MAINTAINABILITY,
        "Deeply nested control flow",
        "Nested control-flow depth is at least 5.",
        Severity.LOW,
        2,
        8,
        "AST nesting is a structural proxy.",
        "Use guard clauses or extract nested behavior.",
        threshold_key="nesting_depth",
        threshold_value=5,
        confidence=Confidence.MEDIUM,
        heuristic=True,
    ),
    _rule(
        "RI-MAINT-006",
        Category.MAINTAINABILITY,
        "Duplicated-looking function structure",
        "Structurally identical normalized function ASTs have at least 8 statements.",
        Severity.MEDIUM,
        3,
        9,
        "This is duplicated-looking structure, never confirmed duplication.",
        "Review the group before extracting shared behavior.",
        threshold_key="duplicate_statements",
        threshold_value=8,
        confidence=Confidence.LOW,
        heuristic=True,
    ),
    _rule(
        "RI-MAINT-007",
        Category.MAINTAINABILITY,
        "Possible unused private definition",
        "A private definition has no static in-repository reference.",
        Severity.LOW,
        1,
        5,
        "Dynamic use is not resolved; this is only a possible unused definition.",
        "Review dynamic references before removing the definition.",
        confidence=Confidence.LOW,
        heuristic=True,
    ),
    _rule(
        "RI-MAINT-008",
        Category.MAINTAINABILITY,
        "TODO or FIXME marker",
        "A TODO or FIXME marker occurs in eligible source.",
        Severity.INFO,
        1,
        5,
        "A marker is not itself a defect.",
        "Resolve, track, or suppress the marker with rationale.",
        confidence=Confidence.HIGH,
        heuristic=False,
    ),
    _rule(
        "RI-MAINT-009",
        Category.MAINTAINABILITY,
        "Import organization concern",
        "A wildcard import, duplicate import, or non-top-level import occurs outside "
        "recognized contexts.",
        Severity.LOW,
        1,
        6,
        "This is a narrow static organization check with optional and type-checking "
        "contexts excluded.",
        "Normalize imports manually or with a trusted development tool.",
        confidence=Confidence.MEDIUM,
        heuristic=True,
    ),
    _rule(
        "RI-TEST-001",
        Category.TESTING,
        "No discovered Python tests",
        "No Python tests are discovered in recognized or configured locations.",
        Severity.HIGH,
        25,
        25,
        "Static discovery cannot establish whether external tests exist.",
        "Add meaningful behavior-focused tests.",
    ),
    _rule(
        "RI-TEST-002",
        Category.TESTING,
        "Low test-to-source ratio",
        "Test/source LOC ratio below 0.10 deducts 12 at medium severity; otherwise a ratio "
        "below 0.25 deducts 6 at low severity.",
        Severity.MEDIUM,
        12,
        12,
        "LOC is a weak proxy and is never measured runtime coverage.",
        "Add behavior-focused tests for important paths.",
        threshold_key=("test_ratio_medium", "test_ratio_low"),
        threshold_value=(0.10, 0.25),
        confidence=Confidence.LOW,
        heuristic=True,
    ),
    _rule(
        "RI-TEST-003",
        Category.TESTING,
        "Tests outside recognized roots",
        "Tests exist only outside recognized or configured test roots.",
        Severity.LOW,
        5,
        5,
        "Nonstandard layouts may be intentional and can be configured.",
        "Organize tests under a recognized root or configure discovery.",
        confidence=Confidence.MEDIUM,
        heuristic=True,
    ),
    _rule(
        "RI-TEST-004",
        Category.TESTING,
        "Test runner evidence missing",
        "Tests exist without pytest, unittest, tox, nox, or configured-runner evidence.",
        Severity.MEDIUM,
        8,
        8,
        "RepoInsight does not run tests and does not claim they fail.",
        "Document or configure the test runner.",
        confidence=Confidence.MEDIUM,
        heuristic=True,
    ),
    _rule(
        "RI-TEST-005",
        Category.TESTING,
        "CI test invocation missing",
        "CI exists without a recognized test invocation.",
        Severity.MEDIUM,
        8,
        8,
        "Workflow parsing is conservative and never establishes runtime test status.",
        "Add an explicit test command to CI.",
        confidence=Confidence.MEDIUM,
        heuristic=True,
    ),
    _rule(
        "RI-TEST-006",
        Category.TESTING,
        "Coverage evidence missing",
        "Tests exist without coverage configuration or invocation evidence.",
        Severity.LOW,
        4,
        4,
        "No runtime coverage claim is made.",
        "Configure coverage measurement when appropriate.",
        confidence=Confidence.MEDIUM,
        heuristic=True,
    ),
    _rule(
        "RI-DOC-001",
        Category.DOCUMENTATION,
        "Root README missing",
        "No recognized README exists at the repository root.",
        Severity.HIGH,
        20,
        20,
        "Only conventional root README names are recognized.",
        "Add a concise project overview.",
    ),
    _rule(
        "RI-DOC-002",
        Category.DOCUMENTATION,
        "README content incomplete",
        "The README lacks purpose, installation, or usage evidence.",
        Severity.LOW,
        5,
        15,
        "Heading and code-block heuristics cannot judge prose quality.",
        "Add explicit purpose, installation, and usage sections.",
        confidence=Confidence.MEDIUM,
        heuristic=True,
    ),
    _rule(
        "RI-DOC-003",
        Category.DOCUMENTATION,
        "Low public docstring rate",
        "Public module, class, and function docstring rate is below 50%.",
        Severity.MEDIUM,
        8,
        8,
        "Publicness is inferred lexically.",
        "Document public APIs.",
        threshold_key="public_docstring_rate",
        threshold_value=0.50,
        confidence=Confidence.MEDIUM,
        heuristic=True,
    ),
    _rule(
        "RI-DOC-004",
        Category.DOCUMENTATION,
        "Contribution guide missing",
        "No recognized contribution guide is present.",
        Severity.LOW,
        4,
        4,
        "A contribution guide may not suit private projects.",
        "Add a contribution workflow when accepting contributions.",
    ),
    _rule(
        "RI-DOC-005",
        Category.DOCUMENTATION,
        "Release notes missing",
        "No recognized changelog or release-notes file is present.",
        Severity.INFO,
        2,
        2,
        "Git history is not treated as release guidance.",
        "Add release notes when distributing the project.",
    ),
    _rule(
        "RI-DOC-006",
        Category.DOCUMENTATION,
        "Usage examples missing",
        "Neither an examples directory nor a README example block is present.",
        Severity.LOW,
        4,
        4,
        "Static structure cannot judge whether prose contains an implicit example.",
        "Add a minimal realistic example.",
        confidence=Confidence.MEDIUM,
        heuristic=True,
    ),
    _rule(
        "RI-SEC-001",
        Category.SECURITY_HYGIENE,
        "Possible secret",
        "Possible secret identified by a high-specificity suspected-secret pattern.",
        Severity.HIGH,
        10,
        30,
        "Pattern matches are heuristic; values are always redacted before every output boundary.",
        "Rotate or revoke the value and move it to secret storage.",
        confidence=Confidence.MEDIUM,
        heuristic=True,
    ),
    _rule(
        "RI-SEC-002",
        Category.SECURITY_HYGIENE,
        "Dynamic code execution call",
        "An AST call targets eval, exec, or compile.",
        Severity.MEDIUM,
        5,
        15,
        "Static usage alone does not establish exploitability.",
        "Replace with safe parsing or allowlists where applicable.",
        confidence=Confidence.HIGH,
        heuristic=False,
    ),
    _rule(
        "RI-SEC-003",
        Category.SECURITY_HYGIENE,
        "Insecure shell execution pattern",
        "os.system, shell-string execution, or subprocess with shell=True is present.",
        Severity.HIGH,
        8,
        24,
        "Input provenance and runtime context are unknown.",
        "Use argument arrays and avoid shells.",
        confidence=Confidence.HIGH,
        heuristic=False,
    ),
    _rule(
        "RI-SEC-004",
        Category.SECURITY_HYGIENE,
        "Unsafe deserialization pattern",
        "pickle, marshal, or shelve load, or unsafe yaml.load is present.",
        Severity.HIGH,
        8,
        24,
        "Input provenance is unknown.",
        "Use safe formats and loaders for untrusted input.",
        confidence=Confidence.HIGH,
        heuristic=False,
    ),
    _rule(
        "RI-SEC-005",
        Category.SECURITY_HYGIENE,
        "Risky temporary-file handling",
        "tempfile.mktemp or a predictable temporary filename is present.",
        Severity.MEDIUM,
        6,
        12,
        "A race condition is not confirmed by static evidence.",
        "Use secure temporary-file APIs.",
        confidence=Confidence.MEDIUM,
        heuristic=True,
    ),
    _rule(
        "RI-SEC-006",
        Category.SECURITY_HYGIENE,
        "Runtime dependency lacks an exact pin",
        "A runtime dependency declaration lacks an exact pin where its format supports one.",
        Severity.LOW,
        2,
        8,
        "Pin policy varies; constraints and lock files count as compensating evidence.",
        "Adopt a dependency constraint or lock strategy appropriate to the project.",
        confidence=Confidence.MEDIUM,
        heuristic=True,
    ),
    _rule(
        "RI-SEC-007",
        Category.SECURITY_HYGIENE,
        "TLS verification disabled",
        "An HTTP client statically disables TLS verification.",
        Severity.HIGH,
        8,
        16,
        "Test code can be suppressed after review.",
        "Keep TLS certificate verification enabled.",
        confidence=Confidence.HIGH,
        heuristic=False,
    ),
    _rule(
        "RI-REPO-001",
        Category.REPOSITORY_HYGIENE,
        "License metadata missing",
        "Both a license file and SPDX license metadata are missing.",
        Severity.MEDIUM,
        10,
        10,
        "License suitability cannot be inferred.",
        "Add an appropriate license file or SPDX metadata.",
    ),
    _rule(
        "RI-REPO-002",
        Category.REPOSITORY_HYGIENE,
        ".gitignore missing",
        "No .gitignore file exists at the repository root.",
        Severity.LOW,
        5,
        5,
        "Other ignore systems are not equivalent to repository ignore policy.",
        "Add ignores for generated and local files.",
    ),
    _rule(
        "RI-REPO-003",
        Category.REPOSITORY_HYGIENE,
        "Dependency metadata missing",
        "Python source exists without recognized dependency metadata.",
        Severity.MEDIUM,
        8,
        8,
        "Dependencies may be managed externally.",
        "Declare dependencies when applicable.",
    ),
    _rule(
        "RI-REPO-004",
        Category.REPOSITORY_HYGIENE,
        "Packaging configuration missing",
        "Python source exists without recognized packaging or build configuration.",
        Severity.LOW,
        5,
        5,
        "Script-only projects may be valid.",
        "Add packaging configuration if the project is distributable.",
    ),
    _rule(
        "RI-REPO-005",
        Category.REPOSITORY_HYGIENE,
        "CI configuration missing",
        "No recognized checked-in CI configuration is present.",
        Severity.MEDIUM,
        8,
        8,
        "External CI is not observable from repository content.",
        "Add checked-in CI configuration.",
    ),
    _rule(
        "RI-REPO-006",
        Category.REPOSITORY_HYGIENE,
        ".dockerignore missing",
        "A Dockerfile exists without a .dockerignore file.",
        Severity.LOW,
        3,
        3,
        "Only conventional Dockerfile and .dockerignore locations are recognized.",
        "Add a minimal .dockerignore.",
    ),
    _rule(
        "RI-REPO-007",
        Category.REPOSITORY_HYGIENE,
        "Issue and pull-request templates missing",
        "Both issue and pull-request templates are missing.",
        Severity.INFO,
        3,
        3,
        "Small projects may not need collaboration templates.",
        "Add collaboration templates when useful.",
    ),
    _rule(
        "RI-REPO-008",
        Category.REPOSITORY_HYGIENE,
        "Community policies missing",
        "Both a code of conduct and security policy are missing.",
        Severity.INFO,
        2,
        2,
        "Private or small projects may not require public-project policy files.",
        "Add public-project policy where applicable.",
    ),
    _rule(
        "RI-HIST-001",
        Category.MAINTENANCE,
        "Stale reachable history",
        "The newest reachable commit is older than 365 days.",
        Severity.HIGH,
        15,
        15,
        "Stable projects may be intentionally quiet.",
        "State maintenance status or resume maintenance.",
        threshold_key="stale_days",
        threshold_value=365,
        confidence=Confidence.MEDIUM,
        heuristic=True,
    ),
    _rule(
        "RI-HIST-002",
        Category.MAINTENANCE,
        "Low recent commit activity",
        "Repository age is at least 180 days and fewer than 2 commits occur in the last 180 days.",
        Severity.LOW,
        5,
        5,
        "Activity is only a signal; stable software can require few commits.",
        "Document maintenance status and expected cadence.",
        threshold_key=("activity_window_days", "activity_min_commits"),
        threshold_value=(180, 2),
        confidence=Confidence.LOW,
        heuristic=True,
    ),
    _rule(
        "RI-HIST-003",
        Category.MAINTENANCE,
        "Single-contributor history",
        "Repository age is at least 180 days with one distinct reachable contributor.",
        Severity.LOW,
        4,
        4,
        "Git identity is imperfect and solo projects are valid.",
        "Document ownership continuity.",
        threshold_key="single_contributor_min_age_days",
        threshold_value=180,
        confidence=Confidence.LOW,
        heuristic=True,
    ),
    _rule(
        "RI-HIST-004",
        Category.MAINTENANCE,
        "Remote history is partial",
        "Remote bounded history is partial.",
        Severity.INFO,
        0,
        0,
        "This is a limitation only and is never penalized.",
        "Use a local repository when complete reachable history is required.",
    ),
    _rule(
        "RI-HIST-005",
        Category.MAINTENANCE,
        "Git history unavailable",
        "Git metadata or history is unavailable.",
        Severity.INFO,
        0,
        0,
        "The maintenance category is unavailable and is never inferred from file timestamps.",
        "Provide an accessible Git repository to enable maintenance evidence.",
    ),
)

RULE_IDS = frozenset(rule.id for rule in RULE_CATALOG)

if len(RULE_CATALOG) != 41 or len(RULE_IDS) != 41:
    raise RuntimeError("The version 1 rule catalog must contain exactly 41 unique rules")

__all__ = ["RULE_CATALOG", "RULE_IDS"]
